/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Nemesis
 */
public class frmMain extends javax.swing.JFrame {

    
    
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int pLeftHeight=screenSize.height-pHead.getHeight();
        
        Dimension d=new Dimension(pLeft.getWidth(), pLeftHeight);
        
        pLeft.setPreferredSize(d);
        
        
        DropDown ddGeneral=new DropDown(btnGeneral, pGeneral, 200, 10, 5);
        DropDown ddUser=new DropDown(btnEmployee, pUser, 150, 10, 5);
        DropDown ddReport=new DropDown(btnReport, pReport, 100, 10, 5);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pHead = new javax.swing.JPanel();
        btnClose = new controls.ImageButton();
        btnMinimise = new controls.ImageButton();
        pLeft = new javax.swing.JPanel();
        pGeneral = new javax.swing.JPanel();
        btnGeneral = new javax.swing.JButton();
        btnFootBallClub = new javax.swing.JButton();
        btnCompetition = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        btnExpense = new javax.swing.JButton();
        pUser = new javax.swing.JPanel();
        btnEmployee = new javax.swing.JButton();
        btnEmployeeList = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        pReport = new javax.swing.JPanel();
        btnReport = new javax.swing.JButton();
        btnReport1 = new javax.swing.JButton();
        dpContent = new controls.MyDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        setResizable(false);

        pHead.setBackground(new java.awt.Color(240, 240, 240));
        pHead.setPreferredSize(new java.awt.Dimension(976, 65));

        btnClose.setHoverIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Icon/close-hover.png"))); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Icon/close-gray.png"))); // NOI18N
        btnClose.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        btnMinimise.setHoverIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Icon/minimise-hover.png"))); // NOI18N
        btnMinimise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Icon/minimise-gray.png"))); // NOI18N
        btnMinimise.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMinimise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimiseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnMinimiseLayout = new javax.swing.GroupLayout(btnMinimise);
        btnMinimise.setLayout(btnMinimiseLayout);
        btnMinimiseLayout.setHorizontalGroup(
            btnMinimiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        btnMinimiseLayout.setVerticalGroup(
            btnMinimiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pHeadLayout = new javax.swing.GroupLayout(pHead);
        pHead.setLayout(pHeadLayout);
        pHeadLayout.setHorizontalGroup(
            pHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHeadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pHeadLayout.setVerticalGroup(
            pHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMinimise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pLeft.setBackground(new java.awt.Color(34, 45, 49));
        pLeft.setPreferredSize(new java.awt.Dimension(350, 350));

        pGeneral.setBackground(new java.awt.Color(34, 45, 49));
        pGeneral.setPreferredSize(new java.awt.Dimension(320, 50));

        btnGeneral.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnGeneral.setForeground(new java.awt.Color(22, 22, 22));
        btnGeneral.setText("General");
        btnGeneral.setPreferredSize(new java.awt.Dimension(77, 50));

        btnFootBallClub.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnFootBallClub.setForeground(new java.awt.Color(22, 22, 22));
        btnFootBallClub.setText("Football Club");
        btnFootBallClub.setPreferredSize(new java.awt.Dimension(77, 50));

        btnCompetition.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnCompetition.setForeground(new java.awt.Color(22, 22, 22));
        btnCompetition.setText("Competition");
        btnCompetition.setPreferredSize(new java.awt.Dimension(77, 50));

        btnBooking.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnBooking.setForeground(new java.awt.Color(22, 22, 22));
        btnBooking.setText("Booking");
        btnBooking.setPreferredSize(new java.awt.Dimension(77, 50));

        javax.swing.GroupLayout pGeneralLayout = new javax.swing.GroupLayout(pGeneral);
        pGeneral.setLayout(pGeneralLayout);
        pGeneralLayout.setHorizontalGroup(
            pGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFootBallClub, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addComponent(btnCompetition, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addComponent(btnBooking, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        pGeneralLayout.setVerticalGroup(
            pGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGeneralLayout.createSequentialGroup()
                .addComponent(btnGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFootBallClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnExpense.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnExpense.setForeground(new java.awt.Color(22, 22, 22));
        btnExpense.setText("Expense");
        btnExpense.setPreferredSize(new java.awt.Dimension(77, 50));

        pUser.setBackground(new java.awt.Color(34, 45, 49));

        btnEmployee.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(22, 22, 22));
        btnEmployee.setText("Employee");
        btnEmployee.setPreferredSize(new java.awt.Dimension(77, 50));

        btnEmployeeList.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEmployeeList.setForeground(new java.awt.Color(22, 22, 22));
        btnEmployeeList.setText("Employee List");
        btnEmployeeList.setPreferredSize(new java.awt.Dimension(77, 50));
        btnEmployeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeListActionPerformed(evt);
            }
        });

        btnProfile.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(22, 22, 22));
        btnProfile.setText("Profile");
        btnProfile.setPreferredSize(new java.awt.Dimension(77, 50));

        javax.swing.GroupLayout pUserLayout = new javax.swing.GroupLayout(pUser);
        pUser.setLayout(pUserLayout);
        pUserLayout.setHorizontalGroup(
            pUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEmployeeList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pUserLayout.setVerticalGroup(
            pUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUserLayout.createSequentialGroup()
                .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEmployeeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pReport.setBackground(new java.awt.Color(34, 45, 49));

        btnReport.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnReport.setForeground(new java.awt.Color(22, 22, 22));
        btnReport.setText("Report");
        btnReport.setPreferredSize(new java.awt.Dimension(77, 50));

        btnReport1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnReport1.setForeground(new java.awt.Color(22, 22, 22));
        btnReport1.setText("Report 1");
        btnReport1.setPreferredSize(new java.awt.Dimension(77, 50));

        javax.swing.GroupLayout pReportLayout = new javax.swing.GroupLayout(pReport);
        pReport.setLayout(pReportLayout);
        pReportLayout.setHorizontalGroup(
            pReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReport1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pReportLayout.setVerticalGroup(
            pReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pReportLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReport1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        javax.swing.GroupLayout pLeftLayout = new javax.swing.GroupLayout(pLeft);
        pLeft.setLayout(pLeftLayout);
        pLeftLayout.setHorizontalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pLeftLayout.setVerticalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLeftLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(pGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pReport, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(503, Short.MAX_VALUE))
        );

        dpContent.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pHead, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(dpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addComponent(dpContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        String []options={"Sign Out","Exit","Cancel"};

        int n = JOptionPane.showOptionDialog(this,
            "Please choose an option",
            "",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[2]);

        switch(n){
            case 0:
            frmLogin.main(null);
            case 1:
            dispose();
        }
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMinimiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimiseMouseClicked
        setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimiseMouseClicked

    void centerForm(JInternalFrame frm){
        
        
        try{
            
            frm.setSelected(true);
            
            
            Dimension desktopSize = dpContent.getSize();
            Dimension jInternalFrameSize = frm.getSize();
            
            int x=(desktopSize.width - jInternalFrameSize.width)/2;
            int y=(desktopSize.height- jInternalFrameSize.height)/2;
            
            
            if(frm.getX()!=x&&frm.getY()!=y)
                frm.setLocation(x,y);
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    
    void showForm(JInternalFrame frm){
        if(frm.isIcon()){
            try {
                frm.setIcon(false);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage());
            }
        }
    }
    
    public void getForm(JInternalFrame frm){
        showForm(frm);
            
        
        if(frm.getParent()==null)
            dpContent.add(frm);
        
        
        frm.setVisible(true);
                   
        centerForm(frm);
    }
    
    frmEmployeeList employeeList=new frmEmployeeList(this);
    
    private void btnEmployeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeListActionPerformed
        
        getForm(employeeList);
        
    }//GEN-LAST:event_btnEmployeeListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try { 
                    UIManager.setLookAndFeel(UIManager.getLookAndFeel()); 
                } catch(Exception ignored){
                
                }

                
                
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private controls.ImageButton btnClose;
    private javax.swing.JButton btnCompetition;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnEmployeeList;
    private javax.swing.JButton btnExpense;
    private javax.swing.JButton btnFootBallClub;
    private javax.swing.JButton btnGeneral;
    private controls.ImageButton btnMinimise;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnReport1;
    private controls.MyDesktopPane dpContent;
    private javax.swing.JPanel pGeneral;
    private javax.swing.JPanel pHead;
    private javax.swing.JPanel pLeft;
    private javax.swing.JPanel pReport;
    private javax.swing.JPanel pUser;
    // End of variables declaration//GEN-END:variables
}
