/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import controls.MyModel;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import project.Club.IdNameAndImage;
import project.Club.IdNameNoImage;


/**
 *
 * @author Nemesis
 */
public class pClub extends javax.swing.JPanel {

    /**
     * Creates new form pLeague
     */
    
    
    
    
    int selectedRowIndex=-1;
    
    
    MyModel modelClub;
    
    
    void prepareForm(){
        
        
        MouseAdapter mouse=new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.isPopupTrigger()){
                    popUpImage.show(pbImage,e.getX(),e.getY());
                }
            }
        };
        
        pbImage.addMouseListener(mouse);
        
        
        
        
        cbLeague.setModel(Club.getModelCbLeague());
        
        originCbBorder=cbLeague.getBorder();
        
        cbLeague.setSelectedIndex(-1);
    }

    
    Border originCbBorder;
    DefaultComboBoxModel modelCbLeague;
    
    
    
    
    public pClub(JDialog dialog, MyModel modelClub) {
        initComponents();
        
        this.dialog=dialog;
        this.modelClub=modelClub;
        
        
        originImagePath=pbImage.getIconAbsolutePath();
    
        prepareForm();
    }

    
    public pClub(JDialog dialog,MyModel modelClub,int selectedRowIndex){
        initComponents();
        
        this.dialog=dialog;
        this.modelClub=modelClub;
        this.selectedRowIndex=selectedRowIndex;
        originImagePath=pbImage.getIconAbsolutePath();
        
        prepareForm();
        
        String club=modelClub.getValueAt(selectedRowIndex, 1)+"";
        String shortName=modelClub.getValueAt(selectedRowIndex,2)+"";
        String league=((IdNameAndImage)modelClub.getValueAt(selectedRowIndex,3)).getName();
        String imageUrl=(modelClub.getValueAt(selectedRowIndex,4))+"";
        
        
        txtClub.setOriginValueAndSetTxt(club);
        txtShortName.setOriginValueAndSetTxt(shortName);
        
        for(int i=0;i<cbLeague.getItemCount();i++){
            
            
            
            
            if((cbLeague.getItemAt(i)+"").equals(league)){
                cbLeague.setSelectedIndex(-1);
                cbLeague.setSelectedIndex(i);
                break;
            }
        }
        
        File f=new File(imageUrl);
        if(f.exists()){
            ImageIcon icon=new ImageIcon(f.getAbsolutePath());
            pbImage.setIcon(icon);
        }
        
        
        
        
    }
    
    
    JDialog dialog;
    
    
    String originImagePath;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpImage = new javax.swing.JPopupMenu();
        popBrowse = new javax.swing.JMenuItem();
        popRemove = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pFname = new javax.swing.JPanel();
        txtClub = new controls.WaterMarkedTextField("");
        jPictureBox1 = new controls.JPictureBox();
        jSeparator2 = new javax.swing.JSeparator();
        pbImage = new controls.JPictureBox();
        btnConfirm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbLeague = new controls.SubJComboBox();
        pFname1 = new javax.swing.JPanel();
        txtShortName = new controls.WaterMarkedTextField("");
        jPictureBox2 = new controls.JPictureBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        popBrowse.setText("Browse");
        popBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popBrowseActionPerformed(evt);
            }
        });
        popUpImage.add(popBrowse);

        popRemove.setText("Remove");
        popRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popRemoveActionPerformed(evt);
            }
        });
        popUpImage.add(popRemove);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Club Infomation");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Club:");

        pFname.setBackground(new java.awt.Color(255, 255, 255));
        pFname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(176, 186, 190)));

        txtClub.setBackground(new java.awt.Color(255, 255, 255));
        txtClub.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtClub.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtClub.setPreferredSize(new java.awt.Dimension(0, 52));
        txtClub.setWatermarkedText("Club");

        jPictureBox1.setBackground(new java.awt.Color(255, 255, 255));
        jPictureBox1.setBorder(null);
        jPictureBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Icon/football.png"))); // NOI18N
        jPictureBox1.setImageMode(controls.JPictureBox.mode.Center);
        jPictureBox1.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPictureBox1Layout = new javax.swing.GroupLayout(jPictureBox1);
        jPictureBox1.setLayout(jPictureBox1Layout);
        jPictureBox1Layout.setHorizontalGroup(
            jPictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPictureBox1Layout.setVerticalGroup(
            jPictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jSeparator2.setBackground(new java.awt.Color(176, 186, 190));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout pFnameLayout = new javax.swing.GroupLayout(pFname);
        pFname.setLayout(pFnameLayout);
        pFnameLayout.setHorizontalGroup(
            pFnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFnameLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPictureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtClub, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pFnameLayout.setVerticalGroup(
            pFnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFnameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pFnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtClub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPictureBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Icon/football-big.png"))); // NOI18N
        pbImage.setImageMode(controls.JPictureBox.mode.Zoom);

        javax.swing.GroupLayout pbImageLayout = new javax.swing.GroupLayout(pbImage);
        pbImage.setLayout(pbImageLayout);
        pbImageLayout.setHorizontalGroup(
            pbImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        pbImageLayout.setVerticalGroup(
            pbImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        btnConfirm.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("League:");

        cbLeague.setBorder(null);

        pFname1.setBackground(new java.awt.Color(255, 255, 255));
        pFname1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(176, 186, 190)));

        txtShortName.setBackground(new java.awt.Color(255, 255, 255));
        txtShortName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtShortName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtShortName.setPreferredSize(new java.awt.Dimension(0, 52));
        txtShortName.setWatermarkedText("Short name");

        jPictureBox2.setBackground(new java.awt.Color(255, 255, 255));
        jPictureBox2.setBorder(null);
        jPictureBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Icon/football.png"))); // NOI18N
        jPictureBox2.setImageMode(controls.JPictureBox.mode.Center);
        jPictureBox2.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPictureBox2Layout = new javax.swing.GroupLayout(jPictureBox2);
        jPictureBox2.setLayout(jPictureBox2Layout);
        jPictureBox2Layout.setHorizontalGroup(
            jPictureBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPictureBox2Layout.setVerticalGroup(
            jPictureBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jSeparator3.setBackground(new java.awt.Color(176, 186, 190));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout pFname1Layout = new javax.swing.GroupLayout(pFname1);
        pFname1.setLayout(pFname1Layout);
        pFname1Layout.setHorizontalGroup(
            pFname1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFname1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPictureBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtShortName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pFname1Layout.setVerticalGroup(
            pFname1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFname1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pFname1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtShortName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPictureBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Short name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pFname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbLeague, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pFname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)))
                            .addGap(60, 60, 60)
                            .addComponent(pbImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(pFname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbLeague, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pbImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnConfirm)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    FileFilter imageFilter = new FileNameExtensionFilter(
    "Image files", ImageIO.getReaderFileSuffixes());
    
    
    private void popBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popBrowseActionPerformed
        JFileChooser fc=new JFileChooser();
        fc.setFileFilter(imageFilter);
        
        if(fc.showDialog(this, "Open")== JFileChooser.APPROVE_OPTION){
            File f=fc.getSelectedFile();
            
            ImageIcon imageIcon=new ImageIcon(f.getAbsolutePath());
            pbImage.setIcon(imageIcon);
            
            
        }
    }//GEN-LAST:event_popBrowseActionPerformed

    
    
    private void popRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popRemoveActionPerformed
        ImageIcon imageIcon=new ImageIcon(originImagePath);
        pbImage.setIcon(imageIcon);
    }//GEN-LAST:event_popRemoveActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        
        
        if(cbLeague.getSelectedIndex()==-1){
            cbLeague.setBorder(new LineBorder(new Color(203,25,21)));
            return;
        }else{
            cbLeague.setBorder(originCbBorder);
        }
        
        String club=txtClub.getThisText();
        
        IdNameAndImage league=new IdNameAndImage(((IdNameNoImage)cbLeague.getSelectedItem()).getId(),((IdNameNoImage)cbLeague.getSelectedItem()).getName(),((IdNameNoImage)cbLeague.getSelectedItem()).getImage());
        
        
        
        
        
        
        String shortName=txtShortName.getThisText();
        String imageUrl=pbImage.getIconAbsolutePath();
       
        if(selectedRowIndex>=0){
            
            String clubId=modelClub.getValueAt(selectedRowIndex, modelClub.getColumnCount()-1)+"";
            
           
           
            String[] data={club,shortName,league.getId(),imageUrl};
            
            if(Club.update(clubId,data)){
                
                
                
                Object[] obj={club,shortName,league,imageUrl};
                
                for(int i=1;i<=obj.length;i++){
                    modelClub.setValueAt(obj[i-1], selectedRowIndex, i);
                }
                
                
                
                
                
                JOptionPane.showMessageDialog(this, "Updated successful", "",JOptionPane.INFORMATION_MESSAGE);
                
                
            }
            
            
        }else{
            
            
            if(Club.insert(club,shortName,league.getId(),imageUrl)){

                
                String clubId=dataCon.one_cell_value("select max(clubId) from club") +"";
                
                modelClub.addRow(modelClub.getRowCount()+1,club,shortName,league,imageUrl,clubId);
                
                
                txtClub.resetTextField();
                txtShortName.resetTextField();
                cbLeague.setSelectedIndex(-1);
                
                JOptionPane.showMessageDialog(this, "Inserted successful", "",JOptionPane.INFORMATION_MESSAGE);
                
                
                
            }
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private controls.SubJComboBox cbLeague;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private controls.JPictureBox jPictureBox1;
    private controls.JPictureBox jPictureBox2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pFname;
    private javax.swing.JPanel pFname1;
    private controls.JPictureBox pbImage;
    private javax.swing.JMenuItem popBrowse;
    private javax.swing.JMenuItem popRemove;
    private javax.swing.JPopupMenu popUpImage;
    private controls.WaterMarkedTextField txtClub;
    private controls.WaterMarkedTextField txtShortName;
    // End of variables declaration//GEN-END:variables
}
